@startuml modules

component core {
	package globingular.core
}

component persistence {
	package globingular.persistence
}

component ui {
	package globingular.ui
}

component jackson {
    component "core" as jackson.core {
    }
    component "databind" as jackson.databind {
    }
}

persistence ..> jackson.core
persistence ..> jackson.databind



globingular.ui ..> globingular.core
globingular.ui ..> globingular.persistence

component javafx {
	component "fxml" as javafx.fxml {
    }
    component "web" as javafx.web {
    }
    component "base" as javafx.base {
    }
}

'ui ..> javafx
ui ..> javafx.fxml
ui ..> javafx.web
core ..> javafx.base

@enduml
