@startuml US01

title <b>User story 1</b>\nEn bruker har vært på reise i Spania og ønsker loggføre besøket.\nHen skriver inn i appen «ES» for Spania og får besøket loggført.

actor User
User -> "~#countryInput: TextField" as countryInput: "ES"
User -> "~#countryAdd: Button" as countryAdd: *click*
countryAdd -> AppController: onCountryAdd()
AppController -> countryInput: getText()
return "ES"
AppController -> World: getCountryFromCode("ES")
return ~#Spain: Country
AppController -> World: getCountryFromName("ES")
return null
AppController -> CountryCollector: setVisited(#Spain: Country)
CountryCollector -> AppController: *notifyListener: setColor(#Spain: Country, Colors.COUNTRY_VISITED)*
AppController --> User: *Map updated with colored countries*

@enduml

@startuml US04

' Implement when pushed to master

title <b>User story 4</b>\nUser has been in Italy on holiday.\nThey open the app and click on Italy to mark it as visited.

actor User

@enduml
